### ISSUE TITLE
Product Manager raises "No transaction is currently active" exception

### ISSUE THREAD

**Issue by RickieES** [RickieES/localizethat#15]
The Manager GUI forms work on the basis of "I have an open transaction; if I commit it, I open a new one immediately". At some point, that is not true. The exception has been raised while trying to remove an original path:

Exception Description: No transaction is currently active
	at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:121)
	at net.localizethat.gui.tabpanels.ProductManager.delOrigPathButtonActionPerformed(ProductManager.java:1074)
	at net.localizethat.gui.tabpanels.ProductManager.access$600(ProductManager.java:41)
	at net.localizethat.gui.tabpanels.ProductManager$6.actionPerformed(ProductManager.java:500)

**Comment by RickieES** [comment]
Commits https://github.com/RickieES/localizethat/commit/564a811a9791bf22f26a7b77e3190742aaf13174 and https://github.com/RickieES/localizethat/commit/c19a7d739e33336ec253a099d46bc337d43fc8b9 could have fixed this issue, as I can't reproduce it right now.

**Comment by RickieES** [comment]
I'm pretty sure than this finally fix the problem, so closing the issue.
